name: Rust CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    
    - name: Check Rust code
      working-directory: src-tauri
      run: cargo check
    
    - name: Run Rust tests
      working-directory: src-tauri
      run: cargo test
    
    - name: Check Rust formatting
      working-directory: src-tauri
      run: cargo fmt --all -- --check
    
    - name: Run Clippy
      working-directory: src-tauri
      run: cargo clippy -- -D warnings

