name: Test and check for Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: src-tauri
      run: cargo build --verbose
    - name: Run tests
      working-directory: src-tauri
      run: cargo test --verbose
