name: Test for Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    
    # - name: Build
    #   working-directory: src-tauri
    #   run: cargo build --verbose
    - name: Run tests
      working-directory: src-tauri
      run: cargo test --verbose
